package bsoftlabecr.entity;

public enum ResponseType {

    OK(200),
    CONNECTION_ERROR(301),
    DISCONNECTION_ERROR(305),
    DECRYPTION_ERROR(310),
    ENCRYPTION_ERROR(320),
    INITIALISATION_ERROR(330),
    NETWORK_ERROR(340),
    SERIALIZATION_ERROR(350),

    CONSTANTS_XML_FILE_READ_ERROR(351),

    EXIST_PREPAYMENT_REQUEST_XML_FILE_READ_ERROR(352),
    NEW_PREPAYMENT_REQUEST_XML_FILE_READ_ERROR(353),

    FISCAL_REPORT_REQUEST_XML_FILE_READ_ERROR(354),

    EXIST_RETURN_PREPAYMENT_REQUEST_XML_FILE_READ_ERROR(355),
    NEW_ORIGINAL_RETURN_PREPAYMENT_REQUEST_XML_FILE_READ_ERROR(356),
    NEW_PARTIAL_RETURN_PREPAYMENT_REQUEST_XML_FILE_READ_ERROR(357),

    EXIST_RETURN_SALE_REQUEST_XML_FILE_READ_ERROR(358),
    NEW_ORIGINAL_RETURN_SALE_REQUEST_XML_FILE_READ_ERROR(359),
    NEW_PARTIAL_RETURN_SALE_REQUEST_XML_FILE_READ_ERROR(360),

    EXIST_SALE_REQUEST_XML_FILE_READ_ERROR(361),
    NEW_SALE_REQUEST_XML_FILE_READ_ERROR(362),

    CASH_REGISTER_RESPONSE_XML_FILE_WRITE_ERROR(370),
    EXIST_PREPAYMENT_RESPONSE_XML_FILE_WRITE_ERROR(371),
    NEW_PREPAYMENT_RESPONSE_XML_FILE_WRITE_ERROR(372),

    EXIST_RETURN_PREPAYMENT_RESPONSE_XML_FILE_WRITE_ERROR(373),
    NEW_ORIGINAL_RETURN_PREPAYMENT_RESPONSE_XML_FILE_WRITE_ERROR(374),
    NEW_PARTIAL_RETURN_PREPAYMENT_RESPONSE_XML_FILE_WRITE_ERROR(375),

    EXIST_RETURN_SALE_RESPONSE_XML_FILE_WRITE_ERROR(376),
    NEW_ORIGINAL_RETURN_SALE_RESPONSE_XML_FILE_WRITE_ERROR(377),
    NEW_PARTIAL_RETURN_SALE_RESPONSE_XML_FILE_WRITE_ERROR(378),

    EXIST_SALE_RESPONSE_XML_FILE_WRITE_ERROR(379),
    NEW_SALE_RESPONSE_XML_FILE_WRITE_ERROR(380);

    private Integer code;

    ResponseType(Integer code) {
        this.code = code;
    }
    public Integer getCode() {
        return this.code;
    }
}
